import { hoodie1, hoodie2, hoodie3, key1, key2, key3 } from "../../public/Img";

export const cardsData = [
    {  id:1, 
        img: key1,
        name: "Nike Air Jordan-01",
        price: "$200.20",
    },
    {id:2,
        img: key2,
        name: "Nike Air Jordan-10",
        price: "$210.20",
    },
    {id:3,
        img: key3,
        name: "Nike Air Jordan-100",
        price: "$220.20",
    },
   
    {id:4,
        img: hoodie1,
        name: "Nike Air Jordan-001",
        price: "$230.20",
    },
    {id:5,
        img: hoodie2,
        name: "Nike Air Jordan-001",
        price: "$230.20",
    },
    {id:6,
        img: hoodie3,
        name: "Nike Air Jordan-001",
        price: "$230.20",
    },
];